import 'package:flutter_test/flutter_test.dart';
import 'package:html_text/src/helper.dart';

void main() {
  test('Texto com imagem', () {
    HtmlTextHelper.mountText(
        '<p>A sonda caçadora de exoplanetas Kepler encontrou aquele que talvez seja o corpo celeste mais parecido com a Terra. A Nasa anunciou, nesta quinta-feira (23), a descoberta de Kepler-452b, um exoplaneta encontrado dentro de uma zona habitável de seu sistema solar, ou seja, uma região onde é possível que exista água no estado líquido. A semelhança com nosso planeta é tão grande que os pesquisadores chamaram o Kepler-452b de Terra 2.0. O Kepler-452b é cerca de 60% maior que a Terra e precisa de 385 dias para completar uma órbita ao redor de sua estrela, a Kepler 452. E essa estrela hospedeira é muito parecida com nosso Sol: tem quase o mesmo tamanho, temperatura e emite apenas 20% mais luz. Localizado na constelação Cygnus, o sistema solar da Terra 2.0 está a 1400 anos-luz distante do nosso.&nbsp;<\/p><p>Fonte: http:\/\/exame.abril.com.br\/tecnologia\/noticias\/terra-2-0-nasa-anuncia-descoberta-historica-de-planeta-quase-identico-ao-nosso, acessado em: 14 de julho de 2016.&nbsp;<\/p><p><br><\/p><p>Supondo-se que, a fim de investigar mais de perto o Kepler-452b, uma sonda tenha sido enviada da Terra por uma equipe da Nasa, com uma velocidade igual a <img width=\"38\" src=\"https:\/\/saladosaber.com.br\/public\/uploads\/courses\/lessons\/2609_626b_1124_3de2.png\" class=\"fr-fic fr-dii\">Quando o relógio instalado na sonda marcar 28 anos de viagem, quanto tempo terá se passado para a equipe na Terra?&nbsp;<\/p>');
    HtmlTextHelper.mountText(
        '<p style=\"text-align: justify;\">(PUC RS) Utilize as partículas β<sup>+<\/sup> (beta-mais), β<sup>–<\/sup> (beta-menos) e α (alfa) para completar as lacunas dos decaimentos radioativos abaixo:<\/p><p style=\"text-align: justify;\"><img width=\"198\" src=\"https:\/\/saladosaber.com.br\/public\/uploads\/courses\/lessons\/1507_b93e_0907_ad27.png\" class=\"fr-fic fr-dii\"><\/p><p style=\"text-align: justify;\">Considerando que <img width=\"15\" src=\"https:\/\/saladosaber.com.br\/public\/uploads\/courses\/lessons\/1507_bece_0907_ad27.png\" class=\"fr-fic fr-dii\"> e <img width=\"15\" src=\"https:\/\/saladosaber.com.br\/public\/uploads\/courses\/lessons\/1507_0bc3_0907_ad27.png\" class=\"fr-fic fr-dii\">&nbsp;são, respectivamente, as representações do anti-neutrino do elétron e do neutrino do elétron, o correto preenchimento das lacunas, de cima para baixo, é<\/p>');
    HtmlTextHelper.mountText(
        '<p style=\"text-align: justify;\">\"De começo, e fosse qual fosse, após a exploração cabralina, a importância dosconhecimentos geográficos sobre o Brasil, o interesse de D. Manuel pelos seus novosterritórios da América foi, ao que parece, mais de ordem estratégica que econômica.\"<img class=\"fr-fic fr-dib\" src=\"https:\/\/saladosaber.com.br\/public\/uploads\/courses\/lessons\/0606_0d90_1027_6e28.png\"><\/p><p style=\"text-align: justify;\">Segundo o historiador português, Jaime Cortesão, no início do século XVI, a importânciaeconômica dada à América pelo Estado português foi de ordem estratégica. Isto, porque:<\/p>",');

    expect(true, true);
  });
}
